"""Add is_owner to admins

Revision ID: 7bf05e4fc531
Revises: 8a7ecd8ab01d
Create Date: 2026-09-01 16:30:42.774796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf05e4fc531'
down_revision = '8a7ecd8ab01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('is_owner')

    # ### end Alembic commands ###
