"""Initial database schema

Revision ID: 8a7ecd8ab01d
Revises: 
Create Date: 2026-08-28 18:00:07.901869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7ecd8ab01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('caption', sa.String(length=250), nullable=False),
    sa.Column('image', sa.String(length=2048), nullable=False),
    sa.Column('image_id', sa.String(length=2048), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('thumbnail_1x', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_2x', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_alt', sa.String(length=100), nullable=False),
    sa.Column('thumbnail_id', sa.String(length=2048), nullable=False),
    sa.Column('url_name', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('admins')
    # ### end Alembic commands ###
